### ISSUE TITLE
W64devkit compiles with warnings, compiled exe can't read qwen 2.5 0.5b safetensors

### ISSUE THREAD

**Issue by JohnClaw** [pierrel55/llama_st#2]
W64devkit log:

src/utils/numa_w.c: In function 'numa_alloc':
src/utils/numa_w.c:162:13: warning: implicit declaration of function 'VirtualAllocExNuma'; did you mean 'VirtualAllocEx'? [-Wimplicit-function-declaration]
  162 |   void *p = VirtualAllocExNuma(GetCurrentProcess(), NULL, sz, MEM_RESERVE | MEM_COMMIT, PAGE_READWRITE, node);
      |             ^~~~~~~~~~~~~~~~~~
      |             VirtualAllocEx
src/utils/numa_w.c:162:13: warning: initialization of 'void *' from 'int' makes pointer from integer without a cast [-Wint-conversion]

Llama_st.exe log:

llama_st run_json/32.json
read file run_json/32.json
CPU flags: f16c:1 fma3:1, sse4.2:1 avx:1 avx2:1
conv/matmul AVX2 checks done.
load tokenizer: C:/mdl/tokenizer.json
load transformer..
read model config in: C:/mdl/config.json
torch float type: bf16
numa node(s): 1, mp node: 0, num logical/physical procs.: 8/8 (HT off)
processor(s) used: 8 in 1 node(s).
node 0 procs: 0,1,2,3,4,5,6,7,
load: C:/mdl/model.safetensors

ERROR: read error in file 'C:/mdl/model.safetensors'

I attached json file if it is needed.
[qwen_0.5b.json](https://github.com/user-attachments/files/17994365/qwen_0.5b.json)

**Comment by pierrel55** [comment]
Hi,

> warning: initialization of 'void *' from 'int' 

Yes this is a "wrong" warning that GCC should not produce. (no warning with VS)

To avoid warning you must define -D_GCC_BLD

This is done by default if you use make_gcc.txt makefile (make -f make_gcc.txt all)

About file error, 

Is file C:/mdl/model.safetensors present in path ?

Is model_num_safetensors value correct ? (1 for single file)

Regards,

**Comment by JohnClaw** [comment]
> Hi,
> 
> > warning: initialization of 'void *' from 'int'
> 
> Yes this is a "wrong" warning that GCC should not produce. (no warning with VS)
> 
> To avoid warning you must define -D_GCC_BLD
> 
> This is done by default if you use make_gcc.txt makefile (make -f make_gcc.txt all)
> 
> About file error,
> 
> Is file C:/mdl/model.safetensors present in path ?
> 
> Is model_num_safetensors value correct ? (1 for single file)
> 
> Regards,

I used make -f make_gcc.txt all but warning displays anyways. Model.safetensors is in path, model_num_safetensors is correct (1 for qwen 2.5 0.5b which is represented by single file). I compiled your repo with Visual Studio Express 2012 and all works fine: qwen 2.5 0.5b, qwen 2.5 7b instruct. But when i compile repo with w64devkit, llama_st.exe can't read safetensors file. May i hope for llama_st.dll, please? I spent whole day trying to force Deepseek to make dll out of main.c and chat.c but my attempt failed due to errors which occured during compilation of dll project in Visual Studio Express 2012.

**Comment by pierrel55** [comment]
I just retested the GCC version with w64devkit (version 1.21.0).
I have no warning when compiling and the executable works.
What version are you using?

Regarding a dll, what functions do you want to interface?

**Comment by JohnClaw** [comment]
> I just retested the GCC version with w64devkit (version 1.21.0). I have no warning when compiling and the executable works. What version are you using?
> 
> Regarding a dll, what functions do you want to interface?

I use this w64devkit: https://github.com/skeeto/w64devkit/releases/download/v2.0.0/w64devkit-x64-2.0.0.exe

I would like to see chat function or at least ability to ask llm a question via dll function call and receive a string variable containing an answer.

This is how it could be called from BCX (https://www.bcxbasiccoders.com/):

```
DECLARE FUNCTION ai$ LIB "llama_st.dll" ALIAS "get_answer_from_ai"(json_file AS STRING, question AS STRING) AS STRING

DIM answer AS STRING

answer = ai$("run_qwen2.5.json", "Why Moon has no oxygen on it's surface?")

PRINT answer

```

**Comment by pierrel55** [comment]
Hi,
You would need a series of functions to do what you want using dll.
One to initialize the llm that returns a handle.
Then query and control functions.
This would be interesting to do, but would take some time to define a convenient API to use.

A better solution I think would be to use a separate process and use TCP to make requests.
I could do it but I'm pretty busy on another project right now. Maybe later.

About GCC you are using the latest version which apparently poses a problem.
Maybe you can use version 1.21.0 if you don't want to use VS.
Personally I rarely use GCC because I don't have a Windows GCC IDE with debugger.

**Comment by JohnClaw** [comment]
> You would need a series of functions to do what you want using dll. One to initialize the llm that returns a handle. Then query and control functions. This would be interesting to do, but would take some time to define a convenient API to use.
> 
> A better solution I think would be to use a separate process and use TCP to make requests. I could do it but I'm pretty busy on another project right now. Maybe later.

API would be better, of course. However, i accept any solution with appreciation. Goodluck with another project. I wait and hope that when you will have enough time you will make api or separate process with tcp.

P.S: Adding support for Phi and Gemma llms would be great too.

**Comment by pierrel55** [comment]
I'm thinking about a version using a UDP client/server to keep it simple without being bothered by thread blocking.
This would also allow running the llm on a separate machine because it uses a lot of resources.
This should be pretty quick to do for a basic version.

**Comment by JohnClaw** [comment]
> Maybe you can use version 1.21.0 if you don't want to use VS.

It works. But llama_st compiled with w64devkit uses only 80% of cpu cores while llama_st compiled with MS Visual Studio Express 2012 uses all 100% of cpu cores as it supposed to do. Can it be fixed somehow?

**Comment by JohnClaw** [comment]
> I'm thinking about a version using a UDP client/server to keep it simple without being bothered by thread blocking. This would also allow running the llm on a separate machine because it uses a lot of resources. This should be pretty quick to do for a basic version.

I forced qwen 2.5 32b coder instruct to make simplified one-shot dll version of llama_st. It can't handle continuos talk but it can answer single question. There are some little bugs (it doesn't stop generating text until esc key is pressed, etc) but it answers my question and this is great. 

BCX code:

DECLARE FUNCTION ai$ LIB "llama_st.dll" ALIAS "get_answer_from_ai"(sent_question$, command_line$)
ai$("Why cats can't bark?", "run_json/modified_qwen_json.json")

C code of modified main.c for compilation with w64devkit:

```
#include "l_util.h"
#include "model.h"
#include "term_utf8.h"  // Include for term_init, text_color, print_sys
#include <stdio.h>      // Include for snprintf and printf

#ifdef CHECK_EXIT
#include "mem_alloc.h"
#include "omp_numa.h"
#endif

// Define color constants
enum e_col_id {
    col_sys = 0,           // system messages
    col_usr,               // user input (keyboard)
    col_llm,               // llm generation
};

// Function prototypes
void term_init(void);
void text_color(int col_id);
int read_key(void);
void forward_user_tokens(bool display, bool def_logits, char *response, size_t response_size);
void tokenizer_decode_print_ex(int token_id, float prob, char *response, size_t response_size);

// Function to be exported
__declspec(dllexport) char* get_answer_from_ai(const char* sent_question, const char* command_line) {
    // Allocate memory for the response
    static char response[4096] = {0};

    // Initialize the model with the provided command line
    if (APP_ERROR()) {
        strcpy(response, "Error initializing model.");
        return response;
    }

    // Build the model with the provided command line
    build_model(command_line);

    // Check if the run mode is chat
    if (model.config.run_mode != run_mode_chat) {
        strcpy(response, "Run mode is not chat.");
        free_model();
        return response;
    }

    // Initialize chat configuration
    struct chat_cfg_t *chat = &model.config.chat;
    const struct run_conf_t *conf = &model.config;
    struct tokenizer_t *tokenizer = &model.tokenizer;
    struct transformer_t *transformer = &model.transformer;
    struct sampler_t *sampler = &model.sampler;

    int pr_mode = chat->chat_prompt_mode;
    const char *sys_prompt, *user_prompt;
    const char *sys_template, *user_template0, *user_template, *end_template;
    bool def_sys_prompt, use_user_template0;

    // Initialize console to enable colors
    if (chat->chat_use_colors)
        term_init();

    // Initialize templates and prompts for mode
    if (pr_mode == 0) {
        switch (conf->e_model_id) {
            case model_id_llama2:
            case model_id_code_llama:
                sys_template = "<s>[INST] <<SYS>>\n%s\n<</SYS>>\n\n";
                user_template0 = "%s [/INST] ";   // llama2 use a first user template
                user_template  = "<s>[INST] %s [/INST] ";
                end_template   = "</s>";
                break;
            case model_id_llama3:
            case model_id_llama31:
                sys_template = "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n%s<|eot_id|>";
                user_template0 = NULL;
                user_template  = "<|start_header_id|>user<|end_header_id|>\n\n%s<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n";
                end_template   = "<|eot_id|>\n";
                break;
            case model_id_mistral:
            case model_id_mathstral:
                sys_template = NULL;             // no sys template ?
                user_template0 = NULL;
                user_template  = "<s>[INST] %s [/INST]";
                end_template   = "</s>\n";
                break;
            case model_id_qwen2:
                sys_template = "system\n%s\n";
                user_template0 = NULL;
                user_template  = "user\n%s\n";
                end_template   = "\n";
                break;
            default:
                strcpy(response, "chat_prompt_mode = 0 not supported for model.");
                free_model();
                return response;
        }
        sys_prompt     = chat->cm0_sys_prompt;
        user_prompt    = chat->cm0_user_prompt;
    } else if (pr_mode == 1) {
        sys_template   = chat->cm1_sys_template;
        user_template0 = chat->cm1_user_first_template;
        user_template  = chat->cm1_user_template;
        sys_prompt     = chat->cm1_sys_prompt;
        user_prompt    = chat->cm1_user_prompt;
        end_template   = chat->cm1_end_template;
    } else if (pr_mode == 2) {
        sys_template   = chat->cm2_sys_template;
        user_template0 = NULL;
        user_template  = chat->cm2_user_template;
        sys_prompt     = chat->cm2_sys_prompt;
        user_prompt    = chat->cm2_user_prompt;
        end_template   = chat->cm2_user_name_sw;
    } else {
        strcpy(response, "invalid chat prompt mode configuration.");
        free_model();
        return response;
    }

    // Reset and keep current prompt
    transformer->state.cache.n_tokens = 0;
    def_sys_prompt = sys_template && sys_template[0];
    use_user_template0 = user_template0 && user_template0[0];

    // System prompt
    while (def_sys_prompt) {
        int str_fwd_len = 0;
        if (!sys_prompt || !sys_prompt[0]) {
            sys_prompt = "";
        }
        str_fwd_len = snprintf(response, sizeof(response), sys_template, sys_prompt);
        sys_prompt = NULL;
        if ((str_fwd_len < 0) || (str_fwd_len == sizeof(response))) {
            strcpy(response, "prompt is too long.");
            free_model();
            return response;
        }
        def_sys_prompt = false;
        tokenizer_encode(response);
        forward_user_tokens(false, false, response, sizeof(response));
        transformer->state.cache.n_tokens_sys = transformer->state.cache.n_tokens;
        break;
    }

    // User prompt
    while (1) {
        int str_fwd_len = 0;
        const char *u_tpl = use_user_template0 ? user_template0 : user_template;

        str_fwd_len = snprintf(response, sizeof(response), u_tpl, sent_question);
        user_prompt = NULL;
        if ((str_fwd_len < 0) || (str_fwd_len == sizeof(response))) {
            strcpy(response, "prompt is too long.");
            free_model();
            return response;
        }
        use_user_template0 = false;
        tokenizer_encode(response);
        forward_user_tokens(false, true, response, sizeof(response));
        break;
    }

    // Get LLM reply
    int pos_reply = transformer->state.cache.n_tokens;
    while (1) {
        struct prob_index_t *pi = sampler_sample();

        if (read_key() == 27) {
            pi->index = model.config.token_eos;
        }

        if ((pi->index == model.config.token_eot) || (pi->index == model.config.token_eos)) {
            tokenizer_encode(end_template);
            forward_user_tokens(false, false, response, sizeof(response));
            break;
        }

        tokenizer_decode_print_ex(pi->index, pi->prob, response, sizeof(response));

        forward(pi->index, true, true);
    }

    // Free the model
    free_model();

    return response;
}

// Function definitions
static void print_sys(const char *str)
{
    text_color(col_sys);
    msg_info(str);
}

void tokenizer_decode_print_ex(int token_id, float prob, char *response, size_t response_size) {
    struct run_conf_t *conf = &model.config;
    char token_str[1024];
    tokenizer_decode_print(token_id, conf->tok_disp_raw);  // Adjusted to match the function signature
    strncat(response, token_str, response_size - strlen(response) - 1);  // Fixed syntax error

    if (conf->tok_disp_prob && (prob >= 0.0f)) {
        char prob_str[64];
        snprintf(prob_str, sizeof(prob_str), "[%.2f],", prob);
        strncat(response, prob_str, response_size - strlen(response) - 1);  // Fixed syntax error
    } else if (conf->tok_disp_prob || conf->tok_disp_split) {
        strncat(response, ",", response_size - strlen(response) - 1);  // Fixed syntax error
    }
}

void forward_user_tokens(bool display, bool def_logits, char *response, size_t response_size) {
    struct tokenizer_t *tokenizer = &model.tokenizer; 
    int i, n_token = tokenizer->mt_list.n_list;
    int def_logits_i = def_logits ? n_token - 1 : -1;

    if (display)
        text_color(col_usr);
    for (i = 0; i < n_token; i++) {
        int tok_id = tokenizer->mt_list.mt[i].tok_id;
        if (display)
            tokenizer_decode_print_ex(tok_id, -1.0f, response, response_size);
        forward(tok_id, false, i == def_logits_i);
    }
    if (display)
        print_sys("\n");
}

int main(int argc, char *argv[]) {
    if (APP_ERROR())                 // catch error return point
        return -1;

    // Predefined arguments
    const char* sent_question = "Why cats can't bark?";
    const char* command_line = "run_json/modified_qwen_json.json";

    // Call the get_answer_from_ai function
    char* response = get_answer_from_ai(sent_question, command_line);

    // Print the response
    printf("Response: %s\n", response);

    return 0;
}
```

Compilation command line for w64devkit:

:: Define the compiler flags and definitions
set DEF=-D_GCC_BLD -DPACK_KV_CACHE -DUSE_THRD_BATCH -DUSE_SA_SIMD
set INC=-Isrc\utils -Isrc -Isrc\matmul -Isrc\model\load -Isrc\model
set COMP=gcc -fopenmp -m64 -march=native -O3 %DEF% %INC%

:: Create the lib directory if it doesn't exist
if not exist lib mkdir lib

:: Source files
set SRC=src\matmul\matmul.c src\matmul\matmul_f8.c src\matmul\matmul_f12.c src\matmul\matmul_f16.c src\matmul\matmul_bf16.c src\matmul\matmul_f32.c src\matmul\matmul_sf16.c src\model\load\json.c src\model\load\load_tokenizer.c src\model\load\load_transformer.c src\model\model.c src\model\omp_numa.c src\model\sampler.c src\model\tokenizer.c src\model\transformer.c src\model\kv_cache.c src\utils\l_util.c src\utils\mem_alloc.c src\utils\numa_w.c src\utils\term_utf8_w.c src\utils\time_ev.c src\utils\utf8.c src\generate.c src\main.c

:: Compile the libraries
%COMP% -c src\model\model.c -o lib\model.o
%COMP% -c src\utils\term_utf8_w.c -o lib\term_utf8_w.o
%COMP% -c src\utils\l_util.c -o lib\l_util.o
%COMP% -c src\matmul\tr_opt_simd.c -o lib\tr_opt_simd.o

:: Create static libraries
ar rcs lib\libmodel.a lib\model.o
ar rcs lib\libterm_utf8.a lib\term_utf8_w.o
ar rcs lib\libll_util.a lib\l_util.o
ar rcs lib\tr_opt_simd.a lib\tr_opt_simd.o

:: Compile the shared library
%COMP% -shared -fPIC -o llama_st.dll %SRC% -Llib -lmodel -lterm_utf8 -lll_util -ltr_opt_simd

**Comment by JohnClaw** [comment]
All files (modified main.c, bat file to build dll (all source files and source folders should be placed into bin subfolder of w64devkit, bat also should be placed in bin subfolder of w64devkit and should be launched in w64devkit.exe), modified json, bcx source of main app, compiled dll and compiled main app) are packed in zip archive attached to this post.
[llama_st_dll.zip](https://github.com/user-attachments/files/18053212/llama_st_dll.zip)

**Comment by pierrel55** [comment]
>  But llama_st compiled with w64devkit uses only 80% of cpu cores while llama_st compiled with MS Visual Studio Express 2012 uses all 100% of cpu cores as it supposed to do. Can it be fixed somehow?
 
I had noticed that GCC was a bit slower in execution but I didn't look into it further.
Maybe you can try to reduce the number of cores used.
In some configurations using all cores reduces performance, this is probably due to memory accesses.
(I don't have time to rework the project at the moment.)

>  it doesn't stop generating text until esc key is pressed
 
Maybe you can check if end of text token(s) is/are correctly defined for qwen.

**Comment by JohnClaw** [comment]
> Maybe you can try to reduce the number of cores used.
> In some configurations using all cores reduces performance, this is probably due to memory accesses.

Thanks for answer and advices. In my case executable made with MS Visual Studio Express 2012 uses all threads of cpu and it makes it work faster than executable made with w64devkit which uses only 80% of cpu threads. I will try to fix the problem with qwen, deepseek, llama 405b etc.
