### ISSUE TITLE
Error on loading Llama 2 model.

### ISSUE THREAD

**Issue by JohnClaw** [pierrel55/llama_st#3]
Hi. I downloaded Slovenian llama 2 model from hf: https://huggingface.co/sambanovasystems/SambaLingo-Slovenian-Chat
After that i put all files of the llm to C:\slovenian and renamed tokenizer_config.json to tokenizer.json because this model doesn't have tokenizer.json.

Then i modified run_llama2.json accordingly and renamed it to slovenian.json.
When i attempted to run slovenian.json with llama_st.exe i got this error:

```
C:\dvkt21\bin>llama_st.exe run_json/slovenian.json
read file run_json/slovenian.json
CPU flags: f16c:1 fma3:1, sse4.2:1 avx:1 avx2:1
conv/matmul AVX2 checks done.
load tokenizer: C:/slovenian/tokenizer.json

ERROR: json: interpret failed (empty key value) line 30: ..pecial": true } }, "additional_special_tokens": [

```
Can it be fixed somehow? Help me, please. I attached slovenian.json and tokenizer.json to this post.
[slovenian_json.zip](https://github.com/user-attachments/files/18211240/slovenian_json.zip)
[tokenizer_json.zip](https://github.com/user-attachments/files/18211248/tokenizer_json.zip)

**Comment by pierrel55** [comment]
Hi,
You cannot simply rename tokenizer_config.json to produce tokenizer.json.
The two files describe different things.
You need a model that include tokenizer.json, or to generate the file with python tools.

**Comment by JohnClaw** [comment]
> Hi, You cannot simply rename tokenizer_config.json to produce tokenizer.json. The two files describe different things. You need a model that include tokenizer.json, or to generate the file with python tools.

Thanks for answer. Where can i find such tool?

**Comment by pierrel55** [comment]
You need to use python AI tools on Linux, but I don't know how to produce the file. AI forums can help you.
